### ISSUE TITLE
question about SafeAreaProvider

### ISSUE THREAD

**Issue by fukemy** [niku98/react-native-dropdown-select#1]
Hi, I want to ask why i need to wrap the whole App by SafeAreaProvider?

**Comment by niku98** [comment]
I need to use safeAreaFrame and safeAreaInsets, which are provided by SafeAreaProvider. They are necessary to calculate doprdown position on screen.

> Hi, I want to ask why i need to wrap the whole App by SafeAreaProvider?

**Comment by fukemy** [comment]
thanks, I used your lib and it's work as expected
